### ISSUE TITLE
Unable to change install directory

### ISSUE THREAD

**Issue by 1Canna** [persiafighter/UnturnedServerManager#3]
I have run the executable and I have no space on my drive to install it at the location I included at the beginning of the unturned.exe 

However, now I am unable to set a new location when running the .exe on the same machine is there an entry added to the pc somewhere that holds the install location?

**Comment by Pustalorc** [comment]
Check next to the executable, there will be a folder named `config` which includes all the settings the software ever needs/uses, which includes the installation path. You can change it there manually or delete that file so the program runs the first start dialog once again.

**Comment by 1Canna** [comment]
Thanks Of course theres a folder there called config im just blind.  haha
